"""add_book_costs_table

Revision ID: 6d3e85fd8843
Revises: c3a4b5d6e7f8
Create Date: 2026-03-09 21:36:26.104551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d3e85fd8843'
down_revision: Union[str, None] = 'c3a4b5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_costs',
    sa.Column('category', sa.String(length=50), nullable=False, comment='Maliyet kategorisi'),
    sa.Column('description', sa.String(length=500), nullable=False, comment='Açıklama'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Tutar (TL)'),
    sa.Column('is_per_unit', sa.Boolean(), nullable=False, comment='Birim başına mı (sipariş × tutar) yoksa sabit maliyet mi'),
    sa.Column('product_id', sa.UUID(), nullable=True, comment='Belirli ürüne ait ise ürün ID, NULL = tüm ürünler'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Aktif mi (pasif maliyetler hesaplamaya dahil edilmez)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Ek notlar'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_book_costs_active', 'book_costs', ['is_active', 'category'], unique=False)
    op.create_index('idx_book_costs_product', 'book_costs', ['product_id'], unique=False, postgresql_where='product_id IS NOT NULL')
    op.drop_table('invoice_serial_counters')
    op.drop_table('coloring_book_products_backup')
    op.alter_column('ai_generation_configs', 'image_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('ai_generation_configs', 'image_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('ai_generation_configs', 'image_width',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ai_generation_configs', 'image_height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ai_generation_configs', 'image_quality',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('ai_generation_configs', 'style_prefix',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ai_generation_configs', 'style_suffix',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ai_generation_configs', 'story_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('ai_generation_configs', 'story_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('ai_generation_configs', 'story_temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ai_generation_configs', 'story_max_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ai_generation_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ai_generation_configs', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ai_generation_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_generation_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('idx_ai_configs_active'), table_name='ai_generation_configs')
    op.drop_index(op.f('idx_audit_order_action_time'), table_name='audit_logs')
    op.create_index('idx_logs_admin', 'audit_logs', ['admin_id'], unique=False, postgresql_where='admin_id IS NOT NULL')
    op.create_index('idx_logs_user', 'audit_logs', ['user_id'], unique=False, postgresql_where='user_id IS NOT NULL')
    op.alter_column('book_templates', 'page_width_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('book_templates', 'page_height_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('book_templates', 'bleed_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('book_templates', 'image_dpi',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('book_templates', 'image_format',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('book_templates', 'default_page_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('book_templates', 'min_page_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('book_templates', 'max_page_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('book_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('book_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('book_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('book_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('idx_book_templates_active'), table_name='book_templates')
    op.alter_column('child_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('child_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('coloring_book_products', 'line_art_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'canny'::character varying"))
    op.alter_column('coloring_book_products', 'edge_threshold_low',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('80'))
    op.alter_column('coloring_book_products', 'edge_threshold_high',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('200'))
    op.alter_column('coloring_book_products', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('coloring_book_products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('coloring_book_products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_table_comment(
        'coloring_book_products',
        existing_comment='DEPRECATED: Use products table with product_type=coloring_book. Kept for backward compatibility.',
        schema=None
    )
    op.create_index('idx_consent_user', 'consent_records', ['user_id'], unique=False, postgresql_where='user_id IS NOT NULL')
    op.drop_constraint(op.f('homepage_sections_section_type_key'), 'homepage_sections', type_='unique')
    op.drop_index(op.f('idx_homepage_sections_type'), table_name='homepage_sections')
    op.drop_index(op.f('idx_homepage_sections_visible'), table_name='homepage_sections')
    op.create_index(op.f('ix_homepage_sections_section_type'), 'homepage_sections', ['section_type'], unique=True)
    op.create_unique_constraint(None, 'invoices', ['story_preview_id'])
    op.alter_column('learning_outcomes', 'ai_prompt',
               existing_type=sa.TEXT(),
               comment='Exact instruction for AI story generation with {child_name} placeholder',
               existing_nullable=True)
    op.alter_column('learning_outcomes', 'ai_prompt_instruction',
               existing_type=sa.TEXT(),
               comment='Detailed AI instruction - preferred over ai_prompt',
               existing_comment='Detailed AI instruction with {child_name} placeholder - preferred over ai_prompt',
               existing_nullable=True)
    op.alter_column('learning_outcomes', 'banned_words_tr',
               existing_type=sa.TEXT(),
               comment='V2: Comma-separated TR words banned from story output when flag active',
               existing_nullable=True)
    op.alter_column('learning_outcomes', 'keywords_tr',
               existing_type=sa.TEXT(),
               comment="Comma-separated TR keywords for story validation (e.g. 'diş,fırça,fırçalama')",
               existing_comment='Comma-separated TR keywords for story validation',
               existing_nullable=True)
    op.alter_column('learning_outcomes', 'keywords_en',
               existing_type=sa.TEXT(),
               comment="Comma-separated EN keywords for story validation (e.g. 'brush,toothbrush,teeth')",
               existing_comment='Comma-separated EN keywords for story validation',
               existing_nullable=True)
    op.alter_column('learning_outcomes', 'visual_hints_en',
               existing_type=sa.TEXT(),
               comment="Comma-separated EN visual hints for image prompts (e.g. 'toothbrush,brushing teeth')",
               existing_comment='Comma-separated EN visual hints for image prompts',
               existing_nullable=True)
    op.alter_column('notification_outbox', 'channel',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'email'::character varying"))
    op.alter_column('notification_outbox', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('notification_outbox', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('notification_outbox', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_preferences', 'email_order_updates',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('notification_preferences', 'email_marketing',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notification_preferences', 'sms_order_updates',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notification_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_pages_order_number'), table_name='order_pages')
    op.alter_column('orders', 'is_coloring_book',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_orders_child_name_trgm'), table_name='orders', postgresql_ops={'child_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_orders_stuck_processing'), table_name='orders', postgresql_where="(((status)::text = 'PROCESSING'::text) AND (generation_started_at IS NOT NULL))")
    op.drop_index(op.f('idx_orders_user'), table_name='orders')
    op.drop_index(op.f('idx_orders_user_created'), table_name='orders')
    op.create_index('idx_orders_user_created', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.alter_column('page_templates', 'page_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('page_templates', 'page_width_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'210'::double precision"))
    op.alter_column('page_templates', 'page_height_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'297'::double precision"))
    op.alter_column('page_templates', 'bleed_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'3'::double precision"))
    op.alter_column('page_templates', 'image_width_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('page_templates', 'image_height_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('page_templates', 'image_x_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('page_templates', 'image_y_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('page_templates', 'image_aspect_ratio',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('page_templates', 'text_width_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('page_templates', 'text_height_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('page_templates', 'text_x_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('page_templates', 'text_y_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('page_templates', 'text_position',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('page_templates', 'font_family',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('page_templates', 'font_size_pt',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('page_templates', 'font_color',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('page_templates', 'text_align',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('page_templates', 'line_height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('page_templates', 'background_color',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('page_templates', 'margin_top_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('page_templates', 'margin_bottom_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('page_templates', 'margin_left_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('page_templates', 'margin_right_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('page_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('page_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('page_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('idx_page_templates_type'), table_name='page_templates')
    op.alter_column('products', 'extra_page_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('5.0'))
    op.drop_index(op.f('idx_products_slug'), table_name='products')
    op.create_index('idx_products_slug', 'products', ['slug'], unique=False)
    op.create_unique_constraint(None, 'products', ['slug'])
    op.drop_constraint(op.f('promo_codes_code_key'), 'promo_codes', type_='unique')
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.alter_column('prompt_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scenarios', 'gallery_images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Array of image URLs for carousel gallery',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('scenarios', 'story_prompt_tr',
               existing_type=sa.TEXT(),
               comment='V2: TR story-writing prompt for Gemini PASS-1 (replaces ai_prompt_template)',
               existing_nullable=True)
    op.alter_column('scenarios', 'location_en',
               existing_type=sa.VARCHAR(length=100),
               comment='V2: English location name used in visual prompts',
               existing_nullable=True)
    op.alter_column('scenarios', 'flags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='V2: Flexible flags (no_family, indoor_only …)',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('scenarios', 'default_page_count',
               existing_type=sa.INTEGER(),
               comment='V2: Default page count for story generation',
               existing_nullable=True,
               existing_server_default=sa.text('6'))
    op.alter_column('scenarios', 'marketing_video_url',
               existing_type=sa.TEXT(),
               comment='YouTube embed or direct video URL for scenario marketing panel',
               existing_nullable=True)
    op.alter_column('scenarios', 'marketing_gallery',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Marketing gallery image URLs for scenario product cards',
               existing_nullable=True)
    op.alter_column('scenarios', 'marketing_price_label',
               existing_type=sa.VARCHAR(length=100),
               comment="Display price label e.g. '299 TL'den başlayan fiyatlarla'",
               existing_nullable=True)
    op.alter_column('scenarios', 'marketing_features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Feature bullet points for scenario product cards',
               existing_nullable=True)
    op.alter_column('scenarios', 'marketing_badge',
               existing_type=sa.VARCHAR(length=100),
               comment="Promo badge text e.g. 'Yeni!', 'En Çok Tercih Edilen'",
               existing_nullable=True)
    op.alter_column('scenarios', 'age_range',
               existing_type=sa.VARCHAR(length=50),
               comment="Target age range e.g. '3-8 yaş'",
               existing_nullable=True)
    op.alter_column('scenarios', 'estimated_duration',
               existing_type=sa.VARCHAR(length=50),
               comment="Estimated duration e.g. '15 dakika'",
               existing_nullable=True)
    op.alter_column('scenarios', 'tagline',
               existing_type=sa.VARCHAR(length=255),
               comment='Short tagline for scenario product cards',
               existing_nullable=True)
    op.alter_column('scenarios', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Scenario rating score (0-5)',
               existing_nullable=True)
    op.alter_column('scenarios', 'review_count',
               existing_type=sa.INTEGER(),
               comment='Number of reviews/orders for social proof',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('scenarios', 'linked_product_id',
               existing_type=sa.UUID(),
               comment='Base product whose production settings this scenario inherits',
               existing_nullable=True)
    op.alter_column('scenarios', 'price_override_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Override Product.base_price for this scenario',
               existing_nullable=True)
    op.alter_column('scenarios', 'price_override_extra_page',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Override Product.extra_page_price for this scenario',
               existing_nullable=True)
    op.alter_column('scenarios', 'cover_template_id_override',
               existing_type=sa.VARCHAR(length=36),
               comment='Override Product.cover_template_id for this scenario',
               existing_nullable=True)
    op.alter_column('scenarios', 'inner_template_id_override',
               existing_type=sa.VARCHAR(length=36),
               comment='Override Product.inner_template_id for this scenario',
               existing_nullable=True)
    op.alter_column('scenarios', 'back_template_id_override',
               existing_type=sa.VARCHAR(length=36),
               comment='Override Product.back_template_id for this scenario',
               existing_nullable=True)
    op.alter_column('scenarios', 'ai_config_id_override',
               existing_type=sa.VARCHAR(length=36),
               comment='Override Product.ai_config_id for this scenario',
               existing_nullable=True)
    op.alter_column('scenarios', 'paper_type_override',
               existing_type=sa.VARCHAR(length=100),
               comment="Override Product.paper_type (e.g. 'Kuşe 200gr')",
               existing_nullable=True)
    op.alter_column('scenarios', 'paper_finish_override',
               existing_type=sa.VARCHAR(length=50),
               comment="Override Product.paper_finish (e.g. 'Parlak')",
               existing_nullable=True)
    op.alter_column('scenarios', 'cover_type_override',
               existing_type=sa.VARCHAR(length=50),
               comment="Override Product.cover_type (e.g. 'Yumuşak Kapak')",
               existing_nullable=True)
    op.alter_column('scenarios', 'lamination_override',
               existing_type=sa.VARCHAR(length=50),
               comment='Override Product.lamination',
               existing_nullable=True)
    op.alter_column('scenarios', 'orientation_override',
               existing_type=sa.VARCHAR(length=20),
               comment="Override Product.orientation ('portrait' or 'landscape')",
               existing_nullable=True)
    op.alter_column('scenarios', 'min_page_count_override',
               existing_type=sa.INTEGER(),
               comment='Override Product.min_page_count',
               existing_nullable=True)
    op.alter_column('scenarios', 'max_page_count_override',
               existing_type=sa.INTEGER(),
               comment='Override Product.max_page_count',
               existing_nullable=True)
    op.alter_column('scenarios', 'story_page_count',
               existing_type=sa.INTEGER(),
               comment='Number of AI-generated story pages (e.g. 22). Shown in marketing.',
               existing_nullable=True)
    op.alter_column('scenarios', 'cover_count',
               existing_type=sa.INTEGER(),
               comment='Number of cover pages (front + back = 2). Shown in marketing.',
               existing_nullable=True,
               existing_server_default=sa.text('2'))
    op.alter_column('scenarios', 'greeting_page_count',
               existing_type=sa.INTEGER(),
               comment='Number of greeting/karşılama pages (e.g. 2: dedication + scenario intro).',
               existing_nullable=True,
               existing_server_default=sa.text('2'))
    op.alter_column('scenarios', 'back_info_page_count',
               existing_type=sa.INTEGER(),
               comment='Number of back-info pages (e.g. 1: educational back page).',
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('scenarios', 'outfit_girl',
               existing_type=sa.TEXT(),
               comment='Outfit description for girl characters in this scenario (English, for AI prompts)',
               existing_nullable=True)
    op.alter_column('scenarios', 'outfit_boy',
               existing_type=sa.TEXT(),
               comment='Outfit description for boy characters in this scenario (English, for AI prompts)',
               existing_nullable=True)
    op.drop_index(op.f('idx_scenarios_theme_key'), table_name='scenarios')
    op.alter_column('story_previews', 'is_preview_mode',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('story_previews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('story_previews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_story_previews_email'), table_name='story_previews')
    op.drop_index(op.f('idx_story_previews_status'), table_name='story_previews')
    op.drop_index(op.f('idx_story_previews_token'), table_name='story_previews')
    op.drop_index(op.f('ix_story_previews_abandoned'), table_name='story_previews', postgresql_where="(((status)::text = 'PREVIEW_GENERATED'::text) OR ((status)::text = 'ABANDONED_TRIAL'::text))")
    op.alter_column('user_addresses', 'label',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Ev'::character varying"))
    op.alter_column('user_addresses', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_addresses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('visual_styles', 'true_cfg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='PuLID true_cfg override (NULL = code fallback)',
               existing_nullable=True)
    op.alter_column('visual_styles', 'start_step',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='PuLID start_step override (NULL = code fallback)',
               existing_nullable=True)
    op.alter_column('visual_styles', 'num_inference_steps',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FLUX num_inference_steps override (NULL = default 28)',
               existing_nullable=True)
    op.alter_column('visual_styles', 'guidance_scale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='FLUX guidance_scale override (NULL = default 3.5)',
               existing_nullable=True)
    op.alter_column('visual_styles', 'style_negative_en',
               existing_type=sa.TEXT(),
               comment='V2: style-specific negative prompt tokens (EN)',
               existing_nullable=True)
    op.alter_column('visual_styles', 'leading_prefix_override',
               existing_type=sa.TEXT(),
               comment='Stil leading prefix (Admin’den; doluysa constants yerine kullanılır)',
               existing_nullable=True)
    op.alter_column('visual_styles', 'style_block_override',
               existing_type=sa.TEXT(),
               comment='STYLE: bloğu (Admin’den; doluysa constants yerine kullanılır)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visual_styles', 'style_block_override',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='STYLE: bloğu (Admin’den; doluysa constants yerine kullanılır)',
               existing_nullable=True)
    op.alter_column('visual_styles', 'leading_prefix_override',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Stil leading prefix (Admin’den; doluysa constants yerine kullanılır)',
               existing_nullable=True)
    op.alter_column('visual_styles', 'style_negative_en',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='V2: style-specific negative prompt tokens (EN)',
               existing_nullable=True)
    op.alter_column('visual_styles', 'guidance_scale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='FLUX guidance_scale override (NULL = default 3.5)',
               existing_nullable=True)
    op.alter_column('visual_styles', 'num_inference_steps',
               existing_type=sa.INTEGER(),
               comment='FLUX num_inference_steps override (NULL = default 28)',
               existing_nullable=True)
    op.alter_column('visual_styles', 'start_step',
               existing_type=sa.INTEGER(),
               comment='PuLID start_step override (NULL = code fallback)',
               existing_nullable=True)
    op.alter_column('visual_styles', 'true_cfg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='PuLID true_cfg override (NULL = code fallback)',
               existing_nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_addresses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_addresses', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_addresses', 'label',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Ev'::character varying"))
    op.create_index(op.f('ix_story_previews_abandoned'), 'story_previews', ['status', 'preview_shown_at'], unique=False, postgresql_where="(((status)::text = 'PREVIEW_GENERATED'::text) OR ((status)::text = 'ABANDONED_TRIAL'::text))")
    op.create_index(op.f('idx_story_previews_token'), 'story_previews', ['confirmation_token'], unique=False)
    op.create_index(op.f('idx_story_previews_status'), 'story_previews', ['status'], unique=False)
    op.create_index(op.f('idx_story_previews_email'), 'story_previews', ['parent_email'], unique=False)
    op.alter_column('story_previews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('story_previews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('story_previews', 'is_preview_mode',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('idx_scenarios_theme_key'), 'scenarios', ['theme_key'], unique=False)
    op.alter_column('scenarios', 'outfit_boy',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Outfit description for boy characters in this scenario (English, for AI prompts)',
               existing_nullable=True)
    op.alter_column('scenarios', 'outfit_girl',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Outfit description for girl characters in this scenario (English, for AI prompts)',
               existing_nullable=True)
    op.alter_column('scenarios', 'back_info_page_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of back-info pages (e.g. 1: educational back page).',
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('scenarios', 'greeting_page_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of greeting/karşılama pages (e.g. 2: dedication + scenario intro).',
               existing_nullable=True,
               existing_server_default=sa.text('2'))
    op.alter_column('scenarios', 'cover_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of cover pages (front + back = 2). Shown in marketing.',
               existing_nullable=True,
               existing_server_default=sa.text('2'))
    op.alter_column('scenarios', 'story_page_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of AI-generated story pages (e.g. 22). Shown in marketing.',
               existing_nullable=True)
    op.alter_column('scenarios', 'max_page_count_override',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Override Product.max_page_count',
               existing_nullable=True)
    op.alter_column('scenarios', 'min_page_count_override',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Override Product.min_page_count',
               existing_nullable=True)
    op.alter_column('scenarios', 'orientation_override',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="Override Product.orientation ('portrait' or 'landscape')",
               existing_nullable=True)
    op.alter_column('scenarios', 'lamination_override',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Override Product.lamination',
               existing_nullable=True)
    op.alter_column('scenarios', 'cover_type_override',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Override Product.cover_type (e.g. 'Yumuşak Kapak')",
               existing_nullable=True)
    op.alter_column('scenarios', 'paper_finish_override',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Override Product.paper_finish (e.g. 'Parlak')",
               existing_nullable=True)
    op.alter_column('scenarios', 'paper_type_override',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Override Product.paper_type (e.g. 'Kuşe 200gr')",
               existing_nullable=True)
    op.alter_column('scenarios', 'ai_config_id_override',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Override Product.ai_config_id for this scenario',
               existing_nullable=True)
    op.alter_column('scenarios', 'back_template_id_override',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Override Product.back_template_id for this scenario',
               existing_nullable=True)
    op.alter_column('scenarios', 'inner_template_id_override',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Override Product.inner_template_id for this scenario',
               existing_nullable=True)
    op.alter_column('scenarios', 'cover_template_id_override',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Override Product.cover_template_id for this scenario',
               existing_nullable=True)
    op.alter_column('scenarios', 'price_override_extra_page',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Override Product.extra_page_price for this scenario',
               existing_nullable=True)
    op.alter_column('scenarios', 'price_override_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Override Product.base_price for this scenario',
               existing_nullable=True)
    op.alter_column('scenarios', 'linked_product_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Base product whose production settings this scenario inherits',
               existing_nullable=True)
    op.alter_column('scenarios', 'review_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of reviews/orders for social proof',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('scenarios', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Scenario rating score (0-5)',
               existing_nullable=True)
    op.alter_column('scenarios', 'tagline',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Short tagline for scenario product cards',
               existing_nullable=True)
    op.alter_column('scenarios', 'estimated_duration',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Estimated duration e.g. '15 dakika'",
               existing_nullable=True)
    op.alter_column('scenarios', 'age_range',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Target age range e.g. '3-8 yaş'",
               existing_nullable=True)
    op.alter_column('scenarios', 'marketing_badge',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Promo badge text e.g. 'Yeni!', 'En Çok Tercih Edilen'",
               existing_nullable=True)
    op.alter_column('scenarios', 'marketing_features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Feature bullet points for scenario product cards',
               existing_nullable=True)
    op.alter_column('scenarios', 'marketing_price_label',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Display price label e.g. '299 TL'den başlayan fiyatlarla'",
               existing_nullable=True)
    op.alter_column('scenarios', 'marketing_gallery',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Marketing gallery image URLs for scenario product cards',
               existing_nullable=True)
    op.alter_column('scenarios', 'marketing_video_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='YouTube embed or direct video URL for scenario marketing panel',
               existing_nullable=True)
    op.alter_column('scenarios', 'default_page_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='V2: Default page count for story generation',
               existing_nullable=True,
               existing_server_default=sa.text('6'))
    op.alter_column('scenarios', 'flags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='V2: Flexible flags (no_family, indoor_only …)',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('scenarios', 'location_en',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='V2: English location name used in visual prompts',
               existing_nullable=True)
    op.alter_column('scenarios', 'story_prompt_tr',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='V2: TR story-writing prompt for Gemini PASS-1 (replaces ai_prompt_template)',
               existing_nullable=True)
    op.alter_column('scenarios', 'gallery_images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Array of image URLs for carousel gallery',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('prompt_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.create_unique_constraint(op.f('promo_codes_code_key'), 'promo_codes', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_index('idx_products_slug', table_name='products')
    op.create_index(op.f('idx_products_slug'), 'products', ['slug'], unique=True)
    op.alter_column('products', 'extra_page_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('5.0'))
    op.create_index(op.f('idx_page_templates_type'), 'page_templates', ['page_type', 'is_active'], unique=False)
    op.alter_column('page_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('page_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('page_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('page_templates', 'margin_right_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('page_templates', 'margin_left_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('page_templates', 'margin_bottom_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('page_templates', 'margin_top_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('page_templates', 'background_color',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('page_templates', 'line_height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('page_templates', 'text_align',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('page_templates', 'font_color',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('page_templates', 'font_size_pt',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('page_templates', 'font_family',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('page_templates', 'text_position',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('page_templates', 'text_y_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('page_templates', 'text_x_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('page_templates', 'text_height_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('page_templates', 'text_width_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('page_templates', 'image_aspect_ratio',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('page_templates', 'image_y_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('page_templates', 'image_x_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('page_templates', 'image_height_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('page_templates', 'image_width_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('page_templates', 'bleed_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'3'::double precision"))
    op.alter_column('page_templates', 'page_height_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'297'::double precision"))
    op.alter_column('page_templates', 'page_width_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'210'::double precision"))
    op.alter_column('page_templates', 'page_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index('idx_orders_user_created', table_name='orders')
    op.create_index(op.f('idx_orders_user_created'), 'orders', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_orders_user'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('idx_orders_stuck_processing'), 'orders', ['generation_started_at'], unique=False, postgresql_where="(((status)::text = 'PROCESSING'::text) AND (generation_started_at IS NOT NULL))")
    op.create_index(op.f('idx_orders_child_name_trgm'), 'orders', ['child_name'], unique=False, postgresql_ops={'child_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('orders', 'is_coloring_book',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('idx_pages_order_number'), 'order_pages', ['order_id', 'page_number'], unique=False)
    op.alter_column('notification_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_preferences', 'sms_order_updates',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notification_preferences', 'email_marketing',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notification_preferences', 'email_order_updates',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('notification_outbox', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_outbox', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('notification_outbox', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('notification_outbox', 'channel',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'email'::character varying"))
    op.alter_column('learning_outcomes', 'visual_hints_en',
               existing_type=sa.TEXT(),
               comment='Comma-separated EN visual hints for image prompts',
               existing_comment="Comma-separated EN visual hints for image prompts (e.g. 'toothbrush,brushing teeth')",
               existing_nullable=True)
    op.alter_column('learning_outcomes', 'keywords_en',
               existing_type=sa.TEXT(),
               comment='Comma-separated EN keywords for story validation',
               existing_comment="Comma-separated EN keywords for story validation (e.g. 'brush,toothbrush,teeth')",
               existing_nullable=True)
    op.alter_column('learning_outcomes', 'keywords_tr',
               existing_type=sa.TEXT(),
               comment='Comma-separated TR keywords for story validation',
               existing_comment="Comma-separated TR keywords for story validation (e.g. 'diş,fırça,fırçalama')",
               existing_nullable=True)
    op.alter_column('learning_outcomes', 'banned_words_tr',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='V2: Comma-separated TR words banned from story output when flag active',
               existing_nullable=True)
    op.alter_column('learning_outcomes', 'ai_prompt_instruction',
               existing_type=sa.TEXT(),
               comment='Detailed AI instruction with {child_name} placeholder - preferred over ai_prompt',
               existing_comment='Detailed AI instruction - preferred over ai_prompt',
               existing_nullable=True)
    op.alter_column('learning_outcomes', 'ai_prompt',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Exact instruction for AI story generation with {child_name} placeholder',
               existing_nullable=True)
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_index(op.f('ix_homepage_sections_section_type'), table_name='homepage_sections')
    op.create_index(op.f('idx_homepage_sections_visible'), 'homepage_sections', ['is_visible', 'sort_order'], unique=False)
    op.create_index(op.f('idx_homepage_sections_type'), 'homepage_sections', ['section_type'], unique=False)
    op.create_unique_constraint(op.f('homepage_sections_section_type_key'), 'homepage_sections', ['section_type'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_consent_user', table_name='consent_records', postgresql_where='user_id IS NOT NULL')
    op.create_table_comment(
        'coloring_book_products',
        'DEPRECATED: Use products table with product_type=coloring_book. Kept for backward compatibility.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('coloring_book_products', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('coloring_book_products', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('coloring_book_products', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('coloring_book_products', 'edge_threshold_high',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('200'))
    op.alter_column('coloring_book_products', 'edge_threshold_low',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('80'))
    op.alter_column('coloring_book_products', 'line_art_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'canny'::character varying"))
    op.alter_column('child_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('child_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_book_templates_active'), 'book_templates', ['is_active'], unique=False)
    op.alter_column('book_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('book_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('book_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('book_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('book_templates', 'max_page_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('book_templates', 'min_page_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('book_templates', 'default_page_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('book_templates', 'image_format',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('book_templates', 'image_dpi',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('book_templates', 'bleed_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('book_templates', 'page_height_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('book_templates', 'page_width_mm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index('idx_logs_user', table_name='audit_logs', postgresql_where='user_id IS NOT NULL')
    op.drop_index('idx_logs_admin', table_name='audit_logs', postgresql_where='admin_id IS NOT NULL')
    op.create_index(op.f('idx_audit_order_action_time'), 'audit_logs', ['order_id', 'action', 'created_at'], unique=False)
    op.create_index(op.f('idx_ai_configs_active'), 'ai_generation_configs', ['is_active', 'is_default'], unique=False)
    op.alter_column('ai_generation_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('ai_generation_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_generation_configs', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ai_generation_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ai_generation_configs', 'story_max_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ai_generation_configs', 'story_temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ai_generation_configs', 'story_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ai_generation_configs', 'story_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('ai_generation_configs', 'style_suffix',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ai_generation_configs', 'style_prefix',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ai_generation_configs', 'image_quality',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('ai_generation_configs', 'image_height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ai_generation_configs', 'image_width',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ai_generation_configs', 'image_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ai_generation_configs', 'image_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_table('coloring_book_products_backup',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('base_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('discounted_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('line_art_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('edge_threshold_low', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('edge_threshold_high', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_template_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('invoice_serial_counters',
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_serial', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('prefix', sa.VARCHAR(length=10), server_default=sa.text("'BM'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('year', name=op.f('invoice_serial_counters_pkey'))
    )
    op.drop_index('idx_book_costs_product', table_name='book_costs', postgresql_where='product_id IS NOT NULL')
    op.drop_index('idx_book_costs_active', table_name='book_costs')
    op.drop_table('book_costs')
    # ### end Alembic commands ###
